-- ST-170/171 · Migration 0038 — staff compliance: catalog repair, staff cadence, on_event
-- Phase 4's deterministic floor (invariant 13: deadlines and eligibility are SQL, never
-- LLM). Three parts:
--   1. Credential catalog repair + expansion toward the COMAR 10.07.05.10 personnel
--      file. REPAIRS: CPR interval 365→730 (AHA BLS certifies for two years — the
--      seeded 365 had no regulatory basis); TB re-screen interval flagged as assumed.
--      Every invented interval carries an advisor_note; nothing is auto-cited (D-017).
--   2. Staff-side cadence materialization: the 0009 evaluator transitions staff
--      obligations but never created them ("generated by a later migration" — this is
--      that migration). app.evaluate_staff_compliance mirrors the B1 recurring pattern
--      anchored on employee.hire_date, clinical titles only; its own cron tick.
--   3. trigger_kind='on_event' becomes real (D-016 left it explicitly unimplemented):
--      cadence rules can subscribe to outbox event types; the domain_event trigger
--      materializes the obligation in the same transaction as the event. First
--      subscriber: personnel-file closure within 30 days of identity.separated.
-- @trace: ST-170, ST-171, D-016, D-017, COMAR 10.07.05.10-.11

-- ── 1 · Catalog: advisor notes + repairs + expansion ──────────────────────────────────
alter table public.credential_type add column advisor_note text;

-- Repairs live INSIDE the idempotent function: hosted tenants get them from this
-- migration's call below; fresh local universes (seeds run AFTER migrations and
-- re-insert cpr at 365) get them from seeds/zz_staff_compliance.sql calling the same
-- function. One source, two entry points — the 0028 pattern.
create or replace function app.expand_credential_catalog(p_tenant uuid) returns int
language plpgsql security definer set search_path = public as $$
declare
  v_count int;
begin
  update public.credential_type
     set renewal_interval_days = 730,
         advisor_note = 'Interval corrected 365→730: AHA BLS certifies for two years.'
   where tenant_id = p_tenant and key = 'cpr' and renewal_interval_days is distinct from 730;
  update public.credential_type
     set advisor_note = 'Annual re-screen interval is ASSUMED — verify against current OHCQ/CDC guidance before relying on it.'
   where tenant_id = p_tenant and key = 'tb_screen' and advisor_note is null;

  insert into public.credential_type
    (tenant_id, key, name, category, required_for_roles, renewal_interval_days,
     blocks_scheduling, source_ref, advisor_note)
  values
    (p_tenant, 'lpn_license', 'LPN License', 'license', '{LPN}', 730, true,
     'COMAR 10.07.05.10', null),
    (p_tenant, 'cna_cert', 'CNA Certification', 'certification', '{CNA}', 730, true,
     'COMAR 10.07.05.10',
     'Maryland CNA renewal cycle assumed 2 years — verify with the Board of Nursing.'),
    (p_tenant, 'hha_cert', 'HHA Certification', 'certification', '{HHA}', null, true,
     'COMAR 10.07.05.10',
     'Whether a standalone HHA certificate applies (vs CNA-GNA pathways) is an HR-advisor question.'),
    (p_tenant, 'annual_inservice', 'Annual In-Service Training', 'training',
     '{RN,LPN,CNA,HHA}', 365, false,
     'COMAR 10.07.05.11',
     'COMAR names required TOPICS but no hour count or renewal frequency — annual is policy, not citation. Training lapse raises an obligation; it does not unstaff visits.'),
    (p_tenant, 'drivers_license', 'Driver''s License', 'license', '{}', null, false,
     null, 'Transport-role requirement only — assign per employee, not per title.'),
    (p_tenant, 'auto_insurance', 'Auto Insurance', 'certification', '{}', 365, false,
     null, 'Transport-role requirement only.')
  on conflict (tenant_id, key) do nothing;
  get diagnostics v_count = row_count;
  return v_count;
end $$;
revoke all on function app.expand_credential_catalog(uuid) from public, anon, authenticated;

select app.expand_credential_catalog(t.id) from public.tenant t;

-- ── 2 · Staff cadence: rules + materialization + tick ─────────────────────────────────
create or replace function app.seed_staff_cadence(p_tenant uuid) returns int
language plpgsql security definer set search_path = public as $$
declare
  v_count int;
begin
  insert into public.cadence_rule
    (tenant_id, key, name, applies_to, trigger_kind, interval_days, interval_months,
     grace_days, at_risk_days, severity, comar_source_ref, active, event_type)
  values
    (p_tenant, 'inservice.annual', 'Annual in-service training', 'staff',
     'interval_days', null, 12, 0, 45, 'medium',
     'COMAR 10.07.05.11 — topics cited; annual frequency is agency policy', true, null),
    (p_tenant, 'file_closure.separation', 'Personnel file closure after separation',
     'staff', 'on_event', 30, null, 0, 7, 'medium',
     'Personnel-record closure — retention citation pending counsel (V14)', true,
     'identity.separated')
  on conflict (tenant_id, key) do nothing;
  get diagnostics v_count = row_count;
  return v_count;
end $$;
revoke all on function app.seed_staff_cadence(uuid) from public, anon, authenticated;

alter table public.cadence_rule add column if not exists event_type text;

select app.seed_staff_cadence(t.id) from public.tenant t;

-- Mirrors the 0019 B1 recurring pattern: anchor = last satisfaction, else hire_date.
-- Clinical titles only — 'Office' and 'Coordinator' attract no clinical training duty.
create or replace function app.evaluate_staff_compliance(p_today date default current_date)
returns int
language plpgsql security definer set search_path = public as $$
declare
  v_count int;
begin
  insert into public.obligation (tenant_id, cadence_rule_id, staff_id, due_on, status)
  select e.tenant_id, r.id, e.id,
         (coalesce(
           (select max(o2.satisfied_at)::date
              from public.obligation o2
             where o2.cadence_rule_id = r.id and o2.staff_id = e.id
               and o2.status = 'satisfied'),
           e.hire_date
         ) + app.cadence_period(r.interval_days, r.interval_months))::date,
         'open'
    from public.cadence_rule r
    join public.employee e
      on e.tenant_id = r.tenant_id
     and e.employment_status in ('onboarding','active')
     and e.role_title in ('RN','LPN','CNA','HHA')
    join public.app_user u on u.id = e.id and u.status = 'active'
   where r.active
     and r.applies_to = 'staff'
     and r.trigger_kind = 'interval_days'
     and app.cadence_period(r.interval_days, r.interval_months) is not null
     and not exists (
       select 1 from public.obligation o3
        where o3.cadence_rule_id = r.id and o3.staff_id = e.id
          and o3.status in ('open','at_risk','overdue'));
  get diagnostics v_count = row_count;
  return v_count;
end $$;
revoke all on function app.evaluate_staff_compliance(date) from public, anon, authenticated;
grant execute on function app.evaluate_staff_compliance(date) to service_role;

select cron.schedule('careos_staff_cadence', '10 * * * *',
  $$select app.run_job('staff_cadence', 3600, 'select app.evaluate_staff_compliance()')$$);

-- ── 3 · on_event rules (D-016 closure): the outbox drives obligations ─────────────────
create or replace function app.cadence_on_event() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  -- Staff-subject rules: the event's entity is the app_user the duty attaches to.
  insert into public.obligation (tenant_id, cadence_rule_id, staff_id, due_on, status)
  select new.tenant_id, r.id, new.entity_id,
         (current_date + coalesce(app.cadence_period(r.interval_days, r.interval_months),
                                  make_interval(days => 30)))::date,
         'open'
    from public.cadence_rule r
   where r.active and r.trigger_kind = 'on_event'
     and r.applies_to = 'staff'
     and r.event_type = new.event_type
     and r.tenant_id = new.tenant_id
     and new.entity_id is not null
     and exists (select 1 from public.app_user u where u.id = new.entity_id)
     and not exists (
       select 1 from public.obligation o
        where o.cadence_rule_id = r.id and o.staff_id = new.entity_id
          and o.status in ('open','at_risk','overdue'));
  return null;
end $$;
create trigger trg_cadence_on_event after insert on public.domain_event
  for each row execute function app.cadence_on_event();
